### ISSUE TITLE
Could not parse multiline columns 

### ISSUE THREAD

**Issue by zanpk** [invoice-x/invoice2data#454] opened 2023-01-26 15:51 UTC
Recently I have started using this amazing library. It works well but unfortunately I could not fetch multiline columns.
Is there any support available to fetch multiline columns ?

I have attached sample invoice format kindly [visit this link](https://docdro.id/Tm6wXzM),
my sample template code
```
items_info:
    parser: lines
    start: 'Quantity\s+Product Code\s+Description\s+Price\s+Total'
    end: '\s+Total'
    first_line: (?P<quantity>\d+)\s+(?P<item_code>\w+)\s+(?P<desc>.+)\s+(?P<price>\d+)\s+(?P<amount>\d+))
    line: (?P<description>.+)
```

**Comment by rmilecki** [comment] 2023-01-26 15:58
```
  File "/usr/lib64/python3.6/sre_parse.py", line 869, in parse
    raise source.error("unbalanced parenthesis")
sre_constants.error: unbalanced parenthesis at position 88
```
This is caused by extra closing brace at the end of your `first_line` regex. Drop that unneded char.

If you want whole description to go to the same field, then rename `description` to `desc` in the `line`.

**Closed by rmilecki** 2023-01-26 15:58 UTC

**Comment by zanpk** [comment] 2023-01-26 17:14
thanks for your quick response. Yes you are right its working on this sample format but unfortunately not working on invoice i am working on. It would be very helpful if you can help me on this.
**Issue: description next line is merged with next row (bold in output mentioned below)** 
Kindly visit this[ link for invoice pdf.](https://docdro.id/AxXNXXZ)

templete:
issuer: XYZ

fields:
  amount:
    parser: regex
    regex: Balance Due\.+
    type: float
  date: date\.+
  invoice_number: inv\.+

  items:
    employee_milege:
    parser: lines
    start: 'Quantity\s+Item Code\s+Description\s+Price Each\s+Amount'
    end: '\s+Tax\s+\(\d+.\d+%\)'
    first_line: (?P<quantity>(.+))\s+(?P<item_code>(TRAVEL))\s+(?P<description>.+)\s+(?P<price>(\d+(?:\.\d+)?))\s+(?P<amount>(\d+(?:\.\d+)?))
    line: (?P<description>.+)
    

keywords:
- xyzcompany
options:
  currency: USD
  decimal_separator: "."

Output:
'items': [
{'quantity': '745', 'item_code': 'TRAVEL', 'description': 'TRAVEL: 2-way (round-trip) Air Fare from New York to New Jersey in\nXXXX. - for Steve Smith.\n**3 Custom        This is next line here.                                                                 50.00
       150.00\n3 Custom        Second next line here**
   **50.00                 150.00\n50.00                 100.00**', 'price': '0.58', 'amount': '595.08'}], 'currency': 'USD', 'desc': 'Invoice from XYZ'}

**Comment by rmilecki** [comment] 2023-01-26 21:19
@zanpk: `first_line` is meant to match first line of **every** invoice item. So you need to make sure your `first_line` matches first lines of all **three** items.

Then `line` is meant to handle **extra** item lines in case there is more than one. It applies to your **first** item case which has `XXXX. - for Steve Smith.` in the second line.

So please rewrite your `first_line` regex. Don't make it `(TRAVEL)` specific as that matches only the first invoice item. The correct `first_line` regex has to match all three:

```
      745 TRAVEL           TRAVEL: 2-way (round-trip) Air Fare from New York to New Jersey in                         0.58               595.08
```
```
           3 Custom        This is next line here.                                                                 50.00                 150.00
```
```
           3 Custom        Second next line here                                                                   50.00                 150.00
```

**Comment by rmilecki** [comment] 2023-01-28 11:36
> actually dont want to get all rows that why I filtered with TRAVEL

Too bad you didn't explain your intentions in the first comment.

Your case doesn't exactly fit what `lines` is meant for but you can use some little hack to achieve that.

Make sure that:
1. `first_line` matches `TRAVEL` line
2. `line` matches extra lines (`description for` and `demonstration`)
3. `last_line` matches `3 Custom        This is next line here.                                                                 50.00                 150.00`

With `last_line` specified parsing lines will stop until finding `first_line` match again (which should be never as you have only one `TRAVEL` line).
