### ISSUE TITLE
gvision error

### ISSUE THREAD

**Issue by maitux** [invoice-x/invoice2data#418] opened 2022-10-03 14:39 UTC
with the latest version of google cloud gvision has errors
AttributeError: module 'google.cloud.vision' has no attribute 'types'.
Types has to be removed to work
google_cloud_vision-3.1.3-py2.py3-none-any.whl
google_cloud_storage-2.5.0

**Comment by rmilecki** [comment] 2022-10-03 14:48
Duplicate of https://github.com/invoice-x/invoice2data/issues/323

**Closed by rmilecki** 2022-10-03 14:48 UTC
