### ISSUE TITLE
Unacceptable character #x0091

### ISSUE THREAD

**Issue by darknd** [invoice-x/invoice2data#264] opened 2019-10-29 19:54 UTC
Hi, Im getting this error:

> invoice2data --input-reader gvision --template-folder /home/ubuntu/output/wwwroot/ocr/template/ file.pdf

Traceback (most recent call last):

  File "/usr/local/bin/invoice2data", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/invoice2data/main.py", line 194, in main
    templates += read_templates(os.path.abspath(args.template_folder))
  File "/usr/local/lib/python3.5/dist-packages/invoice2data/extract/loader.py", line 88, in read_templates
    tpl = ordered_load(template_file.read())
  File "/usr/local/lib/python3.5/dist-packages/invoice2data/extract/loader.py", line 36, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
 yaml.reader.ReaderError: unacceptable character #x0091: special characters are not allowed
  in "<unicode string>", position 14

My python version is 3.5.2, running in Ubuntu 16.04.3 LTS.
The gvision global var is setted too.

Any idea? In my local environment (Debian 9 and Python 2.7.16) is working great.

Thank you very much for your time,

**Comment by rmilecki** [comment] 2023-01-22 16:41
Duplicate of https://github.com/invoice-x/invoice2data/issues/239

**Closed by rmilecki** 2023-01-22 16:41 UTC
