### ISSUE TITLE
dataparser 1.1.0 broken due to regex bug 

### ISSUE THREAD

**Issue by simahawk** [invoice-x/invoice2data#371] opened 2022-03-18 12:16 UTC
There's a problem w/ regex lib see https://github.com/scrapinghub/dateparser/issues/1045.
https://pypi.org/project/regex/2022.3.15/ is broken. A fix is available but not yet released.
Meanwhile we have to downgrade to https://pypi.org/project/regex/2022.3.2/

We can pin https://pypi.org/project/dateparser/1.1.1/ to fix this.

Ideally, it should be done in in `invoice2data` too. In any case: now you know why it won't work on new installations ;)

**Comment by rmilecki** [comment] 2023-01-22 10:45
This is a duplicate of https://github.com/invoice-x/invoice2data/issues/370

**Closed by rmilecki** 2023-01-22 10:45 UTC
