### ISSUE TITLE
ERROR:invoice2data.main:No template for FlipkartInvoice.pdf

### ISSUE THREAD

**Issue by gosemathraj** [invoice-x/invoice2data#223] opened 2019-04-24 09:35 UTC
I am trying to extract data from sample invoices present in the project.E.g FlipkartInvoice.pdf provided as a sample along with its template "com.flipkart.WSRetail".It is giving the following error

Invalid Parameter - 350
Error during processing.
ERROR:invoice2data.main:No template for FlipkartInvoice.pdf 

Running it as : 
invoice2data --input-reader tesseract FlipkartInvoice.pdf

Both the template and invoice pdf are present in the same folder.
Any Help?

**Comment by m3nu** [comment] 2019-04-24 09:43
If you use a custom template, you should point `invoice2data` at it. I don't see that in your command. Same folder isn't enough.

We already have a Flipkart template. Maybe you want to use that instead and fix it, so it works on your PDF file?

**Comment by gosemathraj** [comment] 2019-04-24 10:00
Hi, I am not using any custom template or pdf but the ones already present in the project directory.The directory has FlipkartInvoice.pdf and "com.flipkart.WSRetail" template and it also has the json file containing the output data.I am trying to get the same response given in the json file.But don't know what is missing

pdf to be scanned : FlipkartInvoice.pdf (present in the project directory)
template for that pdf : "com.flipkart.WSRetail" (present in the project directory)

running with this command : 
invoice2data --template-folder D:\RajeshG\Projects\OCR\tools\invoice2data\flipkartinvoicedemo --exclude-built-in-templates --input-reader tesseract FlipkartInvoice.pdf

Still getting the same error : 
Invalid Parameter - 350
Error during processing.
ERROR:invoice2data.main:No template for FlipkartInvoice.pdf

Is the syntax proper? Do we need to provide template file path or just folder path ?

**Comment by m3nu** [comment] 2019-04-24 12:47
Then I'm guessing you have a different invoice format than what we support. Have a look at the [template tutorial](https://github.com/invoice-x/invoice2data/blob/master/TUTORIAL.rst) on how to adapt a template.

**Comment by gosemathraj** [comment] 2019-04-29 09:21
Hi, Now i am getting some different error.I guess its a parsing error.
invoice2data --input-reader tesseract --template-folder /home/webwerks/rajeshG/development/Android/Ocr/invoice2data/files/invoice2data-0.3.3/src/invoice2data/extract/templates FlipkartInvoice.pdf 

Error : 
Traceback (most recent call last):
  File "/home/webwerks/.local/bin/invoice2data", line 10, in <module>
    sys.exit(main())
  File "/home/webwerks/.local/lib/python3.5/site-packages/invoice2data/main.py", line 191, in main
    templates += read_templates()
  File "/home/webwerks/.local/lib/python3.5/site-packages/invoice2data/extract/loader.py", line 88, in read_templates
    tpl = ordered_load(template_file.read())
  File "/home/webwerks/.local/lib/python3.5/site-packages/invoice2data/extract/loader.py", line 36, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0082: special characters are not allowed
  in "<unicode string>", position 312

**Comment by m3nu** [comment] 2019-04-29 09:25
I think there is a trick to put YAML into utf8-mode. Not sure we already have that.

**Comment by gosemathraj** [comment] 2019-04-29 09:27
what's the solution ??

**Comment by m3nu** [comment] 2019-04-29 09:31
Make sure your template only uses UTF-8. Try to open it directly with YAML to debug. Your char may be from another char set than UTF-8 (Latin1?)

I believe we already read template files in UTF-8. So there shouldn't be anything to change.

**Comment by rmilecki** [comment] 2023-01-22 16:44
Duplicate of https://github.com/invoice-x/invoice2data/issues/239

**Closed by rmilecki** 2023-01-22 16:44 UTC
Labels: type:support
